/** @type {import('tailwindcss').Config} */
const tailwindConfig = {
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      maxWidth: {
        mobile: "430px",
      },
      colors: {
        common: {
          0: "var(--color-common-0)",
          100: "var(--color-common-100)",
        },
        neutral: {
          10: "var(--color-neutral-10)",
          20: "var(--color-neutral-20)",
          30: "var(--color-neutral-30)",
          40: "var(--color-neutral-40)",
          50: "var(--color-neutral-50)",
          60: "var(--color-neutral-60)",
          70: "var(--color-neutral-70)",
          80: "var(--color-neutral-80)",
          90: "var(--color-neutral-90)",
          95: "var(--color-neutral-95)",
          99: "var(--color-neutral-99)",
        },
        pink: {
          10: "var(--color-pink-10)",
          20: "var(--color-pink-20)",
          30: "var(--color-pink-30)",
          40: "var(--color-pink-40)",
          50: "var(--color-pink-50)",
          60: "var(--color-pink-60)",
          70: "var(--color-pink-70)",
          80: "var(--color-pink-80)",
          90: "var(--color-pink-90)",
          95: "var(--color-pink-95)",
          99: "var(--color-pink-99)",
        },
        beige: {
          10: "var(--color-beige-10)",
          20: "var(--color-beige-20)",
          30: "var(--color-beige-30)",
          40: "var(--color-beige-40)",
          50: "var(--color-beige-50)",
          60: "var(--color-beige-60)",
          70: "var(--color-beige-70)",
          80: "var(--color-beige-80)",
          90: "var(--color-beige-90)",
          95: "var(--color-beige-95)",
          99: "var(--color-beige-99)",
        },
        opacity: {
          0: "var(--opacity-0)",
          5: "var(--opacity-5)",
          12: "var(--opacity-12)",
          22: "var(--opacity-22)",
          28: "var(--opacity-28)",
          43: "var(--opacity-43)",
          52: "var(--opacity-52)",
          61: "var(--opacity-61)",
          74: "var(--opacity-74)",
          88: "var(--opacity-88)",
          100: "var(--opacity-100)",
        },
        primary: {
          subtler: "var(--color-primary-subtler)",
          subtle: "var(--color-primary-subtle)",
          normal: "var(--color-primary-normal)",
          strong: "var(--color-primary-strong)",
          heavy: "var(--color-primary-heavy)",
        },
        label: {
          default: "var(--color-label-default)",
          subtle: "var(--color-label-subtle)",
          subtler: "var(--color-label-subtler)",
        },
        line: {
          normal: "var(--color-line-normal)",
          alternative: "var(--color-line-alternative)",
        },
        background: {
          normal: "var(--color-background-normal)",
          alternative: "var(--color-background-alternative)",
        },
      },
      boxShadow: {
        normal: "var(--shadow-normal)",
        emphasize: "var(--shadow-emphasize)",
        strong: "var(--shadow-strong)",
      },
    },
  },
};
export default tailwindConfig;
